let countries = new Array ( "Afghanistan",
"Albania", "Algeria", "Andorra",
"Angola", "Antarctica", "Antigua and Barbuda",
"Argentina", "Armenia", "Australia",
"Austria", "Azerbaijan", "Bahamas",
"Bahrain", "Bangladesh", "Barbados",
"Belarus", "Belgium", "Belize",
"Benin", "Bermuda", "Bhutan",
"Bolivia", "Bosnia and Herzegovina",
"Botswana",
"Brazil", "Brunei", "Bulgaria",
"Burkina Faso", "Burma", "Burundi",
"Cambodia", "Cameroon", "Canada",
"Cape Verde",
"Central African Republic", "Chad",
"Chile", "China", "Colombia",
"Comoros", "Congo, Democratic Republic",
"Congo, Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia",
"Cuba", "Cyprus", "Czech Republic",
"Denmark",
"Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador",
"Egypt", "El Salvador", "Equatorial Guinea",
"Eritrea", "Estonia", "Ethiopia",
"Fiji", "Finland", "France", "Gabon",
"Gambia", "Georgia", "Germany",
"Ghana",
"Greece", "Greenland", "Grenada",
"Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
"Honduras", "Hong Kong", "Hungary", "Iceland", "India",
"Indonesia", "Iran", "Iraq",
"Ireland", "Israel", "Italy",
"Jamaica", "Japan",
"Jordan", "Kazakhstan", "Kenya",
"Kiribati", "Korea, North", "Korea, South", "Kuwait", "Kyrgyzstan",
"Laos", "Latvia",
"Lebanon", "Lesotho", "Liberia",
"Libya", "Liechtenstein",
"Lithuania", "Luxembourg",
"Macedonia", "Madagascar",
"Malawi", "Malaysia", "Maldives",
"Mali", "Malta", "Marshall Islands",
"Mauritania", "Mauritius", "Mexico",
"Micronesia",
"Moldova", "Mongolia", "Morocco",
"Monaco", "Mozambique", "Namibia",
"Nauru", "Nepal", "Netherlands", "New Zealand",
"Nicaragua", "Niger", "Nigeria",
"Norway", "Oman", "Pakistan",
"Panama", "Papua New Guinea",
"Paraguay", "Peru",
"Philippines", "Poland", "Portugal",
"Qatar", "Romania", "Russia",
"Rwanda", "Samoa", "San Marino", "Sao Tome",
"Saudi Arabia", "Senegal", "Serbia and Montenegro", "Seychelles",
"Sierra Leone", "Singapore",
"Slovakia", "Slovenia",
"Solomon Islands", "Somalia", "South Africa", "Spain", "Sri Lanka",
"Sudan", "Suriname", "Swaziland",
"Sweden",
"Switzerland", "Syria", "Taiwan",
"Tajikistan", "Tanzania", "Thailand",
"Togo", "Tonga", "Trinidad and Tobago",
"Tunisia", "Turkey", "Turkmenistan",
"Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
"Uruguay", "Uzbekistan", "Vanuatu",
"Venezuela", "Vietnam", "Yemen",
"Zambia", "Zimbabwe");

let descriptions = {
    mode: {
        def: 'Filtrará solo los resultados con el mismo orden de palabras que la entrada (por defecto).',
        des: 'Mostrará todos los resultados que contengan la(s) palabras de la búsqueda, sin importar el orden.'
    },
    minLength: {
        def: 'Mostrará las coincidencias de autocompletado al escribir un caracter o más (por defecto).',
        des: 'Mostrará las coincidencias de autocompletado al escribir %value% o más caracteres.'
    },
    max: {
        def: 'Mostrará todas las coincidencias encontradas en las opciones de autocompletado (por defecto).',
        des: 'Mostrará un máximo de %value% coincidencias encontradas en las opciones de autocompletado.'
    },
    delay: {
        def: 'Mostrará las coincidencias encontradas al instante (por defecto).',
        des: 'Mostrará las coincidencias encontradas con un retraso de %value% milisegundos'
    },
    caseSensitive: {
        def: 'La búsqueda no distinguirá entre mayúsculas y minúsculas (por defecto).',
        des: 'La búsqueda distinguirá entre mayúsculas y minúsculas.'
    },
    autoFocus: {
        def: 'No se mostrarán los resultados al obtener el foco (por defecto).',
        des: 'Se mostrarán los resultados al obtener el foco en la entrada de búsqueda.'
    }
};